name: even_assignment
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  collection: any
  dio: any
  flutter:
    sdk: flutter
  flutter_svg: any
  flutter_vector_icons: any
  google_fonts: any
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/nav/
    - assets/icon/
